#Configuration file for Logitech HD Pro Webcam C920

#TODO
device_name: 'HD Pro Webcam C920'
absolute_exposure: 2089
camera_info_url: 'cameraBottom'
camera_name: 'cameraBottom'
brightness: 66
contrast: 50
exposure: 1
focus_absolute: 0
focus_auto: 1 # Can be changed
format_mode: 0 # 0 means MODE_RGB, 2 for MODE_YUYV
frame_id: 'camera'
frame_rate: 12 # Can be changed
gain: 82
height: 448 #480
power_line_frequency: 0
saturation: = 50
sharpness: 142
white_balance_temperature: true
width: 800 #640

